/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndksample_with_androidstudio_NDKManager */

#ifndef _Included_com_example_ndksample_with_androidstudio_NDKManager
#define _Included_com_example_ndksample_with_androidstudio_NDKManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndksample_with_androidstudio_NDKManager
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndksample_1with_1androidstudio_NDKManager_getStringFromNDK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
